### ISSUE TITLE
Serve static files 

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-pages#345]
Implement the ability to route and serve static files (images, documents, videos etc.) from the filesystem

### Todo

- [ ] Implement file router
- [ ] Implement file downloader
- [ ] Allow to configure routing, caching etc through page frontmatter

### Notes

- Investigate if it's possible to add drop-in support for [Flysystem](https://flysystem.thephpleague.com/v1/docs/)
